import { ethers } from "ethers";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { contract } from "../contract";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [signer, setSigner] = useState();
  const [amount, setAmount] = useState("");

  useEffect(() => connectToMetamask, []);

  const connectToMetamask = async () => {
    try {
      const provider = new ethers.providers.Web3Provider(
        window.ethereum,
        "any"
      );
      await provider.send("eth_requestAccounts", []);
      const signer = provider.getSigner();
      setSigner(signer);
      console.log("Account:", await signer.getAddress());
    } catch (err) {
      console.error(err);
    }
  };

  const buyCoffee = async () => {
    try {
      const smartContract = new ethers.Contract(
        contract.address,
        contract.abi,
        signer
      );
      await smartContract.functions.buyCoffee({
        value: ethers.utils.parseEther(amount),
      });
    } catch (err) {
      console.error(err);
      alert("Error buying coffee!");
    }
  };

  const withdraw = async () => {
    try {
      const smartContract = new ethers.Contract(
        contract.address,
        contract.abi,
        signer
      );
      await smartContract.functions.withdraw();
    } catch (err) {
      console.error(err);
      alert("Error withdrawing coffee!");
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Buy me a coffee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        style={{
          height: "100vh",
          width: "100vw",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <input
          type="text"
          value={amount}
          onChange={(e) => setAmount(e.target.value)}
          placeholder="Amount"
        />
        <button onClick={buyCoffee}>Buy Coffee</button>
        <button onClick={withdraw}>Withdraw</button>
      </div>
    </div>
  );
}
